apiVersion: v1
kind: Service
metadata:
  name: transcript-api-service
  labels:
    app: transcript
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: transcript